
var matrixScript = [
  // 0
  [['tank: operator', 2],
   ['',0.6],
   ['neo: tank, i need an exit', 2],
   ['',0.6],
   ['neo: now!',2],
   ['',1],
   ['operator: .', 0.4],
   ['operator: ..', 0.4],
   ['operator: ...', 1],
   ['operator: got one ready', 2],
   ['', 0.6],
   ['operator: subway station, state and balboa.', 2]
  ],
  // 1
  [['...', 0.2],
   ['agent smith: mr. anderson', 2],
   ['',0.6],
   ['agent smith: we meet again', 2],
   ['',2],
   ['trinity: run, neo. run! what is he doing?', 3],
   ['',0.6],
   ['morpheus: he’s beginning to believe.', 2]
  ],
  // 2
  [['agent smith: i’m going to enjoy...', 1.5],
   ['agent smith: watching you die,', 1.5],
   ['agent smith: mr. anderson.', 1.5],
   ['',0.6],
   ['neo: my name is..', 1.2],
   ['',0.6],
   ['neo: n', 0.4],
   ['neo: ne', 0.4],
   ['neo: neo', 0.4],
   ['neo: neo!', 0.2],
   ['neo: neo!!', 0.2],
   ['neo: neo!!!', 0.2],
   ['neo: neo!!!!', 1]
  ],
  // 3
  [['neo: mr. wizard...', 2],
   ['neo: get me the hell out of here.', 3],
   ['',0.6],
   ['tank: got a patch on an old exit...', 2],
   ['tank: wabash and lake.', 2]
  ],
  // 4
  [['',0.6],
   ['.',0.6],
   ['..',0.6],
   ['...',1],
   ['',1],
   ['neo: oh shit...', 1.5],
   ['neo: help.', 1.5],
   ['neo: need a little help.', 1.5]
  ],
  //5
  [['',0.6],
   ['agent smith: i’m going to be honest', 3],
   ['agent smith: i hate this place,', 3],
   ['',0.6],
   ['agent smith: this zoo', 2],
   ['agent smith: this prison', 2],
   ['agent smith: this reality', 2],
   ['agent smith: whatever you want to call it', 3],
   ['agent smith: i can’t stand it any longer.', 3],
   ['',1],
   ['agent smith: it’s the smell', 3],
   ['agent smith: if there is such a thing', 3],
   ['agent smith: i feel.', 0.6],
   ['agent smith: i feel..', 0.6],
   ['agent smith: i feel...', 1.8],
   ['agent smith: saturated by it', 2],
   ['',0.6],
   ['agent smith: i can taste your stink', 2],
   ['agent smith: and every time i do', 2],
   ['agent smith: i feel i have somehow been...', 3],
   ['agent smith: infected by it', 2],
   ['agent smith: it’s repulsive', 2],
   ['agent smith: ', 2],
   ['agent smith: i must get out of here', 2]
  ]
];
